apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
stringData:
  mysql-root-password: rootpassword123
  mysql-user: wordpress
  mysql-password: wordpresspassword123
  mysql-database: wordpress
